## Libraries / Packages

In [96]:
import pandas as pd
import altair as alt
from vega_datasets import data as vega_data

## Data

[nih_merged2_with_traits](../data/nih_merged2_with_traits.csv)

In [97]:
nih_merged2_with_traits = pd.read_csv('/Users/teresabui/Documents/MIDS/DATASCI 209/teamscience/DATASCI-209_flask_teamscience_vercel/data/nih_merged2_with_traits.csv')
print(nih_merged2_with_traits.shape)

(5757, 123)
has_been_terminated
True     3426
False    2331
Name: count, dtype: int64
has_been_reinstated
False    3364
True     2393
Name: count, dtype: int64

In [124]:
# nih_merged2_with_traits[nih_merged2_with_traits['current_status']=="Restored"]
print(nih_merged2_with_traits.value_counts('has_been_terminated'))
print(nih_merged2_with_traits.value_counts('has_been_reinstated'))
print(nih_merged2_with_traits.value_counts("detailed_status"))

has_been_terminated
True     3426
False    2331
Name: count, dtype: int64
has_been_reinstated
False    3364
True     2393
Name: count, dtype: int64
detailed_status
Unfrozen (confirmed)        2185
Reinstated (confirmed)      1903
Terminated                  1234
Reinstated (unconfirmed)     371
Unfrozen (unconfirmed)        48
Frozen                        15
Non-renewal                    1
Name: count, dtype: int64

In [126]:
nih_merged2_with_traits.groupby(['has_been_terminated', 'has_been_reinstated'])['detailed_status'].value_counts().reset_index()

    has_been_terminated  has_been_reinstated           detailed_status  count
0                 False                False      Unfrozen (confirmed)   2166
1                 False                False    Unfrozen (unconfirmed)     47
2                 False                False                    Frozen     15
3                 False                 True    Reinstated (confirmed)     84
4                 False                 True      Unfrozen (confirmed)     19
5                  True                False                Terminated   1136
6                  True                 True    Reinstated (confirmed)   1819
7                  True                 True  Reinstated (unconfirmed)    371
8                  True                 True                Terminated     98
9                  True                 True    Unfrozen (unconfirmed)      1
10                 True                 True               Non-renewal      1

### Data: Transformations and Aggregations

In [100]:
# Load US states topojson
states = alt.topo_feature(vega_data.us_10m.url, 'states')

# Categorizing state into a region
northeast = {'CT','ME','MA','NH','RI','VT','NJ','NY','PA'}
midwest = {'IL','IN','MI','OH','WI','IA','KS','MN','MO','NE','ND','SD'}
south = {'DE','FL','GA','MD','NC','SC','VA','DC','WV','AL','KY','MS','TN','AR','LA','OK','TX'}
west = {'AZ','CO','ID','MT','NV','NM','UT','WY','AK','CA','HI','OR','WA'}

# Assigning states to region
def region(state):
    if state in northeast: return 'Northeast'
    if state in midwest: return 'Midwest'
    if state in south: return 'South'
    if state in west: return 'West'
    return 'Other/Territory'

nih_merged2_with_traits['region'] = nih_merged2_with_traits['org_state'].apply(region)
regional = nih_merged2_with_traits[nih_merged2_with_traits['region'] != 'Other/Territory']

region_stats = regional.groupby('region')['has_been_terminated'].agg(
    n_grants='count', n_terminated='sum', rate='mean'
).reset_index()
region_stats.rate

region_rates = {
    'Northeast': 0.483,
    'Midwest':   0.308,
    'South':     0.950,
    'West':      0.926
}

#### State-level Data - Transformations and Aggregations

In [159]:
# FIPS code → state abbreviation lookup
fips_to_state = {
    1:'AL',2:'AK',4:'AZ',5:'AR',6:'CA',8:'CO',9:'CT',10:'DE',
    11:'DC',12:'FL',13:'GA',15:'HI',16:'ID',17:'IL',18:'IN',
    19:'IA',20:'KS',21:'KY',22:'LA',23:'ME',24:'MD',25:'MA',
    26:'MI',27:'MN',28:'MS',29:'MO',30:'MT',31:'NE',32:'NV',
    33:'NH',34:'NJ',35:'NM',36:'NY',37:'NC',38:'ND',39:'OH',
    40:'OK',41:'OR',42:'PA',44:'RI',45:'SC',46:'SD',47:'TN',
    48:'TX',49:'UT',50:'VT',51:'VA',53:'WA',54:'WV',55:'WI',56:'WY'
}

state_stats = regional.groupby(['region', 'org_state'])['has_been_terminated'].agg(
    n_grants='count', n_terminated='sum', rate='mean'
).reset_index()

state_stats = state_stats.rename(columns={"org_state" : "state"})

state_to_fips = {v: k for k, v in fips_to_state.items()}

state_stats['id'] = state_stats['state'].map(state_to_fips)

state_df = pd.DataFrame([
    {'id': fips, 'state': abbr, 'region': region(abbr),
     'rate': region_rates.get(region(abbr), None)}
    for fips, abbr in fips_to_state.items()
])

    id state     region   rate
0    1    AL      South  0.950
1    2    AK       West  0.926
2    4    AZ       West  0.926
3    5    AR      South  0.950
4    6    CA       West  0.926
5    8    CO       West  0.926
6    9    CT  Northeast  0.483
7   10    DE      South  0.950
8   11    DC      South  0.950
9   12    FL      South  0.950
10  13    GA      South  0.950
11  15    HI       West  0.926
12  16    ID       West  0.926
13  17    IL    Midwest  0.308
14  18    IN    Midwest  0.308
15  19    IA    Midwest  0.308
16  20    KS    Midwest  0.308
17  21    KY      South  0.950
18  22    LA      South  0.950
19  23    ME  Northeast  0.483
20  24    MD      South  0.950
21  25    MA  Northeast  0.483
22  26    MI    Midwest  0.308
23  27    MN    Midwest  0.308
24  28    MS      South  0.950
25  29    MO    Midwest  0.308
26  30    MT       West  0.926
27  31    NE    Midwest  0.308
28  32    NV       West  0.926
29  33    NH  Northeast  0.483
30  34    NJ  Northeast  0.483
31  35    NM       West  0.926
32  36    NY  Northeast  0.483
33  37    NC      South  0.950
34  38    ND    Midwest  0.308
35  39    OH    Midwest  0.308
36  40    OK      South  0.950
37  41    OR       West  0.926
38  42    PA  Northeast  0.483
39  44    RI  Northeast  0.483
40  45    SC      South  0.950
41  46    SD    Midwest  0.308
42  47    TN      South  0.950
43  48    TX      South  0.950
44  49    UT       West  0.926
45  50    VT  Northeast  0.483
46  51    VA      South  0.950
47  53    WA       West  0.926
48  54    WV      South  0.950
49  55    WI    Midwest  0.308
50  56    WY       West  0.926

#### Merging State-level and Regional-level Data/Stats

In [102]:
merged_stats = pd.merge(state_stats, state_df, on="id", how='left')
merged_stats = merged_stats.drop(columns=['region_y', 'state_y'])
merged_stats = merged_stats.rename(columns={"region_x":"region",
                                            "state_x":"state",
                                            "n_grants":"n_grants_state",
                                            "n_terminated":"n_terminated_state",
                                            "rate_x":"rate_state",
                                            "rate_y":"rate_region"})
region_calc = merged_stats.groupby('region').agg(n_grant_region=('n_grants_state', 'sum'),
                                                 n_terminated_region=('n_terminated_state', 'sum')).reset_index()
merged_stats.merge(region_calc, on='region')
merged_stats = merged_stats.merge(region_calc, on='region')

### Terminated and Reinstated

#### Reinstated

In [177]:
terminated_only = regional[regional['has_been_terminated']]

terminated_only['id'] = terminated_only['org_state'].map(state_to_fips)

dummies = pd.get_dummies(terminated_only['detailed_status'], prefix='status')
terminated_only = pd.concat([terminated_only, dummies], axis=1)

got_reinstated = terminated_only.groupby(['id', 'region', 'org_state']).agg(
    n_terminated=('has_been_terminated', 'sum'),
    n_confirmed=('status_Reinstated (confirmed)', 'sum'),
    n_unconfirmed=('status_Reinstated (unconfirmed)', 'sum'))

got_reinstated['n_reinstated'] = got_reinstated['n_confirmed'] + got_reinstated['n_unconfirmed']

got_reinstated['reinstatement_rate'] = (
    got_reinstated['n_reinstated'] / got_reinstated['n_terminated']
)

got_reinstated = got_reinstated.reset_index()

#### Still Terminated

In [178]:
still_terminated = terminated_only.groupby(['id','region', 'org_state']).agg(
    n_terminated=('has_been_terminated', 'sum'),
    n_still_terminated=('status_Terminated', 'sum'))

still_terminated['still_terminated_rate'] = (
    still_terminated['n_still_terminated'] / still_terminated['n_terminated']
)

still_terminated = still_terminated.reset_index()

#### Merging *still_terminated* and *got_reinstated*

In [180]:
merged_rates = pd.merge(got_reinstated, still_terminated, on="id", how='left')
merged_rates = merged_rates.drop(columns=['region_y', 'org_state_y', 'n_terminated_y'])
merged_rates = merged_rates.rename(columns={"region_x":"region",
                                            "org_state_x":"state",
                                            "n_terminated_x":"n_terminated"})
merged_rates

,id,region,state,n_terminated,n_confirmed,n_unconfirmed,n_reinstated,reinstatement_rate,n_still_terminated,still_terminated_rate
0,1,South,AL,26,3,1,4,0.153846,22,0.846154
1,2,West,AK,3,1,0,1,0.333333,2,0.666667
2,4,West,AZ,29,13,11,24,0.827586,5,0.172414
3,5,South,AR,9,0,0,0,0.000000,9,1.000000
4,6,West,CA,808,604,134,738,0.913366,70,0.086634
5,8,West,CO,51,29,20,49,0.960784,2,0.039216
6,9,Northeast,CT,53,20,0,20,0.377358,33,0.622642
7,10,South,DE,7,3,4,7,1.000000,0,0.000000
8,11,South,DC,23,5,2,7,0.304348,16,0.695652
9,12,South,FL,81,17,4,21,0.259259,60,0.740741
10,13,South,GA,67,17,4,21,0.313433,46,0.686567
11,15,West,HI,11,6,5,11,1.000000,0,0.000000
12,16,West,ID,1,0,0,0,0.000000,1,1.000000
13,17,Midwest,IL,71,19,4,23,0.323944,48,0.676056
14,18,Midwest,IN,21,1,1,2,0.095238,19,0.904762
15,19,Midwest,IA,9,1,0,1,0.111111,8,0.888889
16,20,Midwest,KS,2,0,0,0,0.000000,2,1.000000
17,21,South,KY,20,2,0,2,0.100000,18,0.900000
18,22,South,LA,17,3,1,4,0.235294,13,0.764706
19,23,Northeast,ME,5,2,2,4,0.800000,1,0.200000
20,24,South,MD,85,38,16,54,0.635294,31,0.364706
21,25,Northeast,MA,762,617,43,660,0.866142,100,0.131234
22,26,Midwest,MI,68,17,3,20,0.294118,48,0.705882
23,27,Midwest,MN,29,12,9,21,0.724138,8,0.275862
24,28,South,MS,12,2,1,3,0.250000,9,0.750000
25,29,Midwest,MO,40,5,1,6,0.150000,34,0.850000
26,30,West,MT,6,1,0,1,0.166667,5,0.833333
27,31,Midwest,NE,14,2,0,2,0.142857,12,0.857143
28,32,West,NV,8,4,4,8,1.000000,0,0.000000
29,33,Northeast,NH,5,1,0,1,0.200000,4,0.800000
30,34,Northeast,NJ,31,20,7,27,0.870968,4,0.129032
31,35,West,NM,10,9,0,9,0.900000,1,0.100000
32,36,Northeast,NY,359,183,44,227,0.632312,132,0.367688
33,37,South,NC,102,23,3,26,0.254902,76,0.745098
34,38,Midwest,ND,2,0,0,0,0.000000,2,1.000000
35,39,Midwest,OH,43,11,2,13,0.302326,30,0.697674
36,40,South,OK,16,5,2,7,0.437500,9,0.562500
37,41,West,OR,22,10,10,20,0.909091,2,0.090909
38,42,Northeast,PA,108,23,4,27,0.250000,81,0.750000
39,44,Northeast,RI,31,10,1,11,0.354839,20,0.645161
40,45,South,SC,24,3,0,3,0.125000,21,0.875000
41,46,Midwest,SD,2,0,1,1,0.500000,1,0.500000
42,47,South,TN,34,7,2,9,0.264706,25,0.735294
43,48,South,TX,122,10,2,12,0.098361,110,0.901639
44,49,West,UT,14,3,1,4,0.285714,10,0.714286
45,50,Northeast,VT,2,1,0,1,0.500000,1,0.500000
46,51,South,VA,40,6,0,6,0.150000,34,0.850000
47,53,West,WA,57,27,14,41,0.719298,16,0.280702
48,55,Midwest,WI,37,21,6,27,0.729730,10,0.270270

In [183]:
regional_calc2 = merged_rates.groupby('region').agg(
    regional_still_terminated = ('n_still_terminated','sum'),
    regional_n_terminated = ('n_terminated','sum'),
    regional_n_reinstated = ('n_reinstated', 'sum')
)
regional_calc2['regional_still_terminated_rate'] = regional_calc2['regional_still_terminated'] /regional_calc2['regional_n_terminated']
regional_calc2['regional_reinstated_rate'] = regional_calc2['regional_n_reinstated'] /regional_calc2['regional_n_terminated']
merged_rates = pd.merge(merged_rates,regional_calc2,on='region',how='left')

In [184]:
merged_rates.columns

Index(['id', 'region', 'state', 'n_terminated', 'n_confirmed', 'n_unconfirmed',
       'n_reinstated', 'reinstatement_rate', 'n_still_terminated',
       'still_terminated_rate', 'regional_still_terminated',
       'regional_n_terminated', 'regional_n_reinstated',
       'regional_still_terminated_rate', 'regional_reinstated_rate'],
      dtype='str')

### Institution

In [134]:
state_stats = regional.groupby(['region', 'org_state'])['has_been_terminated'].agg(
    n_grants='count', n_terminated='sum', rate='mean'
).reset_index()
state_stats

       region org_state  n_grants  n_terminated      rate
0     Midwest        IA         9             9  1.000000
1     Midwest        IL       820            71  0.086585
2     Midwest        IN        22            21  0.954545
3     Midwest        KS         2             2  1.000000
4     Midwest        MI        69            68  0.985507
5     Midwest        MN        30            29  0.966667
6     Midwest        MO        42            40  0.952381
7     Midwest        ND         2             2  1.000000
8     Midwest        NE        14            14  1.000000
9     Midwest        OH        47            43  0.914894
10    Midwest        SD         2             2  1.000000
11    Midwest        WI        37            37  1.000000
12  Northeast        CT        56            53  0.946429
13  Northeast        MA       818           762  0.931540
14  Northeast        ME         5             5  1.000000
15  Northeast        NH         5             5  1.000000
16  Northeast        NJ        35            31  0.885714
17  Northeast        NY      1471           359  0.244052
18  Northeast        PA       138           108  0.782609
19  Northeast        RI       279            31  0.111111
20  Northeast        VT         3             2  0.666667
21      South        AL        27            26  0.962963
22      South        AR         9             9  1.000000
23      South        DC        24            23  0.958333
24      South        DE         7             7  1.000000
25      South        FL        89            81  0.910112
26      South        GA        69            67  0.971014
27      South        KY        22            20  0.909091
28      South        LA        18            17  0.944444
29      South        MD        85            85  1.000000
30      South        MS        12            12  1.000000
31      South        NC       118           102  0.864407
32      South        OK        16            16  1.000000
33      South        SC        25            24  0.960000
34      South        TN        35            34  0.971429
35      South        TX       125           122  0.976000
36      South        VA        40            40  1.000000
37       West        AK         3             3  1.000000
38       West        AZ        29            29  1.000000
39       West        CA       863           808  0.936269
40       West        CO        51            51  1.000000
41       West        HI        11            11  1.000000
42       West        ID         1             1  1.000000
43       West        MT         6             6  1.000000
44       West        NM        10            10  1.000000
45       West        NV         8             8  1.000000
46       West        OR        22            22  1.000000
47       West        UT        14            14  1.000000
48       West        WA        84            57  0.678571

## Visualization

### Visualization: Map

In [104]:
# Region Selection (Interactive Feature)
region_select = alt.selection_point(
    fields=['region'], 
    bind='legend', 
    toggle='false',
    on='click',
    clear='mouseout',
    name='region_select'
)

# Map 
map_blue = alt.Chart(states).mark_geoshape(
    stroke='white',
    strokeWidth=0.5
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(merged_stats, 'id', ['region', 'n_terminated_region', 'rate_region','state', 'rate_state', 'n_grants_state'])
).encode(
    color=alt.Color('region:N',
        scale=alt.Scale (domain=['Northeast', 'Midwest', 'West', 'South'], 
        range=[ "#F8650C", "#FFC917", "#F00000", "#8C0000"]),
        title='Region'
    ),
    opacity=alt.when(region_select).then(alt.value(1)).otherwise(alt.value(0.35)),
    tooltip=['region:N', 'n_terminated_region:Q', 'state:N','n_grants_state:Q',alt.Tooltip('rate_state:Q', format='.1%')]
).project('albersUsa').properties(
    title='NIH Grant Gross Termination Rates Map',
    width=600,
    height=400
).add_params(
    region_select)
map_blue

alt.Chart(...)

#### Visualization: Map (States)

In [105]:
# Region Selection (Interactive Feature)
state_select = alt.selection_point(
    fields=['state'], 
    toggle='false',
    on='click',
    clear='mouseout',
    name='state_select'
)

# Map 
map_state = alt.Chart(states).mark_geoshape(
    stroke='white',
    strokeWidth=0.5
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(merged_stats, 'id', ['region', 'n_terminated_region', 'rate_region','state', 'rate_state', 'n_grants_state'])
).encode(
    color=alt.Color('rate_state:Q',
        scale=alt.Scale(scheme="yelloworangered"),
        title='States'
    ),
    opacity=alt.when(state_select).then(alt.value(1)).otherwise(alt.value(0.35)),
    tooltip=['state:N','n_grants_state:Q',alt.Tooltip('rate_state:Q', format='.1%')]
).project('albersUsa').properties(
    title='NIH Grant Gross Termination Rates State Map',
    width=600,
    height=400
).add_params(
    state_select)

points = alt.Chart()

map_state

alt.Chart(...)

### Visualization: Rate cards

In [106]:
card = (
    alt.Chart(merged_stats)
    .transform_aggregate(
        rate='mean(rate_region)',
        groupby=['region']
    )
    .mark_text(fontSize=48, fontWeight="bold")
    .encode(
        text=alt.Text('rate:Q', format='.1%'),
        color=alt.Color('region:N',
            scale=alt.Scale(
                domain=['Northeast', 'Midwest', 'West', 'South'],
                range=[ "#F8650C", "#FFC917", "#F00000", "#8C0000"]
            ),
            legend=None
        ),
        opacity=alt.when(region_select).then(alt.value(1)).otherwise(alt.value(0.35))
    )
    .properties(width=150, height=100)
    .facet(
        column=alt.Column('region:N', title=None, header=alt.Header(labelFontSize=12, labelFontWeight='bold')),
    ).properties(
        title= alt.TitleParams('Gross Termination Rate by Region ',
        fontSize=18,
        anchor='middle',
        offset=15)
    )
    .add_params(region_select)
)
card

alt.FacetChart(...)

In [107]:
termination_map_v1 = (card & (map_blue | map_state)).resolve_scale(
    color='independent'
)

termination_map_v1

/var/folders/hx/jtyk6jzj73ddd9stpk75hnc40000gn/T/ipykernel_63463/3651295819.py:1: UserWarning: Automatically deduplicated selection parameter with identical configuration. If you want independent parameters, explicitly name them differently (e.g., name='param1', name='param2'). See https://github.com/vega/altair/issues/3891
  termination_map_v1 = (card & (map_blue | map_state)).resolve_scale(

alt.VConcatChart(...)

### Visualization: Still Terminated and Got Reinstated

In [191]:
# Region Selection (Interactive Feature)
region_select = alt.selection_point(
    fields=['region'], 
    bind='legend', 
    toggle='false',
    on='click',
    clear='mouseout',
    name='region_select'
)

# Map 
map_still_term = alt.Chart(states).mark_geoshape(
    stroke='white',
    strokeWidth=0.5
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(merged_rates, 'id', ['region', 'regional_n_terminated', 'regional_still_terminated_rate'])
).encode(
     color=alt.Color('regional_still_terminated_rate:Q',
            scale=alt.Scale(scheme="yelloworangered"),
            title='Region Rate'
        ),
    opacity=alt.when(region_select).then(alt.value(1)).otherwise(alt.value(0.35)),
    tooltip=['region:N', 'regional_n_terminated:Q', alt.Tooltip('regional_still_terminated_rate:Q', format='.1%')]
).project('albersUsa').properties(
    title='NIH Grant Still Terminated Rates Map',
    width=600,
    height=400
).add_params(
    region_select)
map_still_term

alt.Chart(...)

In [ ]:
# Region Selection (Interactive Feature)
region_select = alt.selection_point(
    fields=['region'], 
    bind='legend', 
    toggle='false',
    on='click',
    clear='mouseout',
    name='region_select'
)

# Map 
map_still_term = alt.Chart(states).mark_geoshape(
    stroke='white',
    strokeWidth=0.5
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(merged_rates, 'id', ['region', 'regional_n_terminated', 'regional_still_terminated_rate'])
).encode(
     color=alt.Color('regional_still_terminated_rate:Q',
            scale=alt.Scale(scheme="yelloworangered"),
            title='Region Rate'
        ),
    opacity=alt.when(region_select).then(alt.value(1)).otherwise(alt.value(0.35)),
    tooltip=['region:N', 'regional_n_terminated:Q', alt.Tooltip('regional_still_terminated_rate:Q', format='.1%')]
).project('albersUsa').properties(
    title='NIH Grant Still Terminated Rates Map',
    width=600,
    height=400
).add_params(
    region_select)
map_still_term